In [1]:
import numpy as np
import cv2
import os
import random
import matplotlib.pyplot as plt
import pickle

In [2]:
DIRECTORY = r'C:\Face-Mask-Detection Model\Dataset\train'
CATEGORIES = ['with_mask', 'without_mask']

In [13]:
IMG_SIZE = 150

data = []
data_path = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    label = CATEGORIES.index(category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        data_path.append(img_path)
        img_arr = cv2.imread(img_path)
        img_arr = cv2.resize(img_arr,(IMG_SIZE,IMG_SIZE))
        data.append([img_arr, label])
    
    print(data[0][0])
    
        
    
        
        

[[[18 40 45]
  [19 40 43]
  [18 37 40]
  ...
  [23 37 35]
  [23 37 35]
  [23 37 35]]

 [[20 42 47]
  [19 40 43]
  [19 38 41]
  ...
  [26 39 37]
  [25 39 37]
  [24 38 36]]

 [[21 43 48]
  [20 41 44]
  [20 39 42]
  ...
  [29 43 41]
  [27 41 39]
  [25 39 37]]

 ...

 [[69 76 66]
  [71 79 69]
  [74 82 72]
  ...
  [66 73 76]
  [67 75 78]
  [68 76 79]]

 [[66 75 65]
  [69 77 67]
  [72 80 70]
  ...
  [77 84 87]
  [76 83 86]
  [75 82 85]]

 [[66 74 64]
  [69 76 67]
  [71 79 69]
  ...
  [87 94 97]
  [85 92 95]
  [84 90 93]]]
[[[18 40 45]
  [19 40 43]
  [18 37 40]
  ...
  [23 37 35]
  [23 37 35]
  [23 37 35]]

 [[20 42 47]
  [19 40 43]
  [19 38 41]
  ...
  [26 39 37]
  [25 39 37]
  [24 38 36]]

 [[21 43 48]
  [20 41 44]
  [20 39 42]
  ...
  [29 43 41]
  [27 41 39]
  [25 39 37]]

 ...

 [[69 76 66]
  [71 79 69]
  [74 82 72]
  ...
  [66 73 76]
  [67 75 78]
  [68 76 79]]

 [[66 75 65]
  [69 77 67]
  [72 80 70]
  ...
  [77 84 87]
  [76 83 86]
  [75 82 85]]

 [[66 74 64]
  [69 76 67]
  [71 79 69]
  .

In [4]:
random.shuffle(data)
random.shuffle(data_path)

In [5]:
X = []
Y = []

for features, labels in data:
    X.append(features)
    Y.append(labels)

In [6]:
X = np.array(X)
Y = np.array(Y)

In [7]:
pickle.dump(X,open('X.pkl','wb'))
pickle.dump(Y,open('Y.pkl','wb'))
